project:
  type: website
  output-dir: docs

website:
  title: "Jelajah Statistika dan Ilmu Data"
  favicon: "favicon.png"
  back-to-top-navigation: true
  google-analytics: G-WTEJLB3562
  open-graph: true
  twitter-card: true
  site-url: https://jelajahstatid.github.io
  repo-url: https://github.com/jelajahstatid/jelajahstatid.github.io
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    right:
      - index.qmd
      - ihwal.qmd
      - icon: github
        href: https://github.com/jelajahstatid/jelajahstatid.github.io
      - icon: rss
        href: index.xml
  page-footer: 
    left: |
      © 2024–2025 Jelajah Statistika dan Ilmu Data
    right: |
      Blog ini dikembangkan dengan [Quarto](https://quarto.org/){.external target="_blank"}.
format:
  html:
    toc: true
    theme: 
      light: [cosmo, tema.scss]
      dark: [cosmo, tema-gelap.scss]
    respect-user-color-scheme: true
    code-fold: true
    code-link: true
    code-tools: true

editor: visual

language: _bahasa.yml

